development:
  adapter: postgresql
  encoding: utf8
  database: ad_site_development
  pool: 5
  username: maksimvoronko
  password: 1234

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ad_site_test
  pool: 5
  username: maksimvoronko
  password: 1234

